# application/json only
# 2 paths: /hello, /add
# /hello: GET, query parameter name, pattern: "^[a-zA-Z]*$"
# /add: GET, query parameters num1, num2, integer type, required: true. The example of num1 is 10, num2 generate
openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /hello:
    get:
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z]*$"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      responses:
        '405':
          description: Method Not Allowed
  /add:
    get:
      parameters:
        - name: num1
          in: query
          required: true
          schema:
            type: integer
            example: 10
        - name: num2
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
    post:
      responses:
        '405':
          description: Method Not Allowed